#!/bin/bash

# Script to help rename remaining images
# Review each image and rename accordingly

GALLERY="/Users/machd/Documents/SERGIK Web and app/web/public/images/gallery"

echo "🖼️  SERGIK Image Renaming Helper"
echo "================================="
echo ""
echo "Current images in gallery:"
ls -1 "$GALLERY" | grep -E '\.(jpg|jpeg)$' | nl
echo ""
echo "📋 Expected filenames (match by description):"
echo ""
echo "1. desert-portrait-1.jpg"
echo "   → Desert landscape, golden hour, profile view, sunglasses"
echo ""
echo "2. rooftop-portrait-1.jpg"
echo "   → Urban rooftop at night, man bun, city lights, Edison bulbs"
echo ""
echo "3. performance-green-1.jpg"
echo "   → Green lighting, geometric stage props, bucket hat, Off-White jacket"
echo ""
echo "4. studio-red-1.jpg"
echo "   → Studio with LED panels, red couch, fedora hat, dog"
echo "   ✅ Already renamed!"
echo ""
echo "5. performance-pioneer-1.jpg"
echo "   → Performance from behind, purple/orange lighting, Off-White logo"
echo ""
echo "6. sunset-portrait-1.jpg"
echo "   → Sunset portrait, palm trees, hands clasped, dark sunglasses"
echo ""
echo "7. performance-red-blue-1.jpg"
echo "   → Red/blue lighting, profile view, Pioneer DJ mixer, Supreme logo"
echo ""
echo "8. performance-group-1.jpg"
echo "   → Group performance, multiple performers, red/blue lighting"
echo "   ✅ Already renamed (Gem & Jam)!"
echo ""
echo "9. performance-closeup-1.jpg"
echo "   → Close-up performance, headphones, angular jacket pattern"
echo ""
echo "💡 To rename manually:"
echo "   cd $GALLERY"
echo "   mv IMG_XXXX.jpg [expected-filename].jpg"
echo ""
echo "Or use this script interactively by editing it."

