// Static admin UI routes for E2E crawl (mirrors app/admin pages).
// Omits auth-only login/setup and dynamic segments such as [id].
export const ADMIN_UI_CRAWL_PATHS: readonly string[] = [
  '/admin',
  '/admin/analytics',
  '/admin/artist',
  '/admin/bundles',
  '/admin/content',
  '/admin/database',
  '/admin/events',
  '/admin/gallery',
  '/admin/instagram',
  '/admin/licenses',
  '/admin/logs',
  '/admin/memberships',
  '/admin/merch',
  '/admin/music',
  '/admin/music-library',
  '/admin/music-vault',
  '/admin/nurturing',
  '/admin/nurturing/analytics',
  '/admin/nurturing/campaigns',
  '/admin/nurturing/fans',
  '/admin/nurturing/segments',
  '/admin/nurturing/smart-links',
  '/admin/nurturing/templates',
  '/admin/purchasable-tracks',
  '/admin/purchases',
  '/admin/releases',
  '/admin/settings',
  '/admin/sonic-dna',
  '/admin/splits',
  '/admin/subscribers',
  '/admin/users',
  '/admin/videos',
  '/admin/videos-manager',
  // Linked from admin nav (not under /admin)
  '/studio',
]
